version: "3.8"

services:
  watchtower:
    container_name: watchtower
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.dev-self-contained
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    command: --interval 10 --http-api-metrics --http-api-token 2664 --debug prometheus grafana parent child
  prometheus-watchtower:
    container_name: prometheus-watchtower
    image: prom/prometheus
    volumes:
      - ./prometheus-watchtower/:/etc/prometheus/
      - prometheus-watchtower:/prometheus/
    ports:
      - 9090:9090
  grafana-watchtower:
    container_name: grafana-watchtower
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana-watchtower:/var/lib/grafana
      - ./grafana-watchtower:/etc/grafana/provisioning
  parent:
    image: nginx
    container_name: parent
  child:
    image: nginx:alpine
    labels:
      com.centurylinklabs.watchtower.depends-on: parent
    container_name: child

volumes:
  prometheus-watchtower: {}
  grafana-watchtower: {}
